package com.github.tyrantsim.jtuo.sim;

public enum PassiveBGE {

    // Placeholder for no-bge:
    NO_BGE,

    // Passive BGEs
    BLOODLUST, BRIGADE, COUNTERFLUX, DIVERT, ENDURINGRAGE, FORTIFICATION, HEROISM,
    ZEALOTSPRESERVATION, METAMORPHOSIS, MEGAMORPHOSIS, REVENGE, TURNINGTIDES, VIRULENCE,
    HALTEDORDERS, DEVOUR, CRITICALREACH, TEMPORALBACKLASH, FURIOSITY, OATH_OF_LOYALTY,
    BLOOD_VENGEANCE, COLDSLEEP,

}
